version: "3"

services:
  backend-redis:
    image: redis:6-alpine
    container_name: "backend-redis"
    ports:
     - 9009:6379
  backend:
    build: ./backend/.
    container_name: "backend"
    volumes:
     - ./Backend:/app
    ports:
     - 9000:3000
    depends_on:
     - "backend-redis"
    environment:
     - REDIS_URL=redis://backend-redis

